name: Dylan Vaughn
favicon: null
layout_spectrum: 0.90868
typography_spectrum: 0.76131
title: 'Dylan Vaughn, Musician'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0e0e10'
    - '#90c9ff'
    - '#e9f2fb'
    - '#8e877f'
    - '#484649'
  brandStrength: 0.4071698319166899
  lightness: 0.19839906436391175
  saturation: 0.3812635079957545
  rhythmicContrast: 0.7481038796249777
purpose: []
